### ISSUE TITLE
有计划支持vue3嘛

### ISSUE THREAD

**Issue by ziyingjie** [wocwin/t-ui#13]

**Comment by ziyingjie** [comment]
antdv 3.0

**Comment by wocwin** [comment]
目前没有计划，后续应该会有

**Comment by wocwin** [comment]
目前已支持vue3+element-plus
https://github.com/wocwin/t-ui-plus

**Comment by wocwin** [comment]
目前已支持vue3+element-plus
https://github.com/wocwin/t-ui-plus

**Comment by mtgq** [comment]
> 目前已支持vue3+element-plus https://github.com/wocwin/t-ui-plus

感谢大佬
