### ISSUE TITLE
vue2 插槽为何不生效？

### ISSUE THREAD

**Issue by Luckbaby** [wocwin/t-ui#16]
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/18533218/169832781-9e45ecfb-bbd1-45bc-bfac-834bd55c2a75.png">
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/18533218/169832874-00c71e12-f777-4c11-a8fc-31d648fe38b1.png">

**Comment by Luckbaby** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
并没有效果，字体没有变色

**Comment by Luckbaby** [comment]
我发现问题的所在了，因为您提供的demo里的数据都是初始化就有的，我的则是从接口里请求到再赋值的，所以插槽样式无效

**Comment by wocwin** [comment]
![image](https://user-images.githubusercontent.com/37534478/169967711-f835bc99-e70c-487b-837c-a84a34a9292d.png)
![image](https://user-images.githubusercontent.com/37534478/169967820-e18430b3-6770-4606-ad55-9d56a0dfd009.png)
我们也是动态加载的数据，能生效，你是不是迁移的组件漏了什么？
