### ISSUE TITLE
table 默认多选不生效，原生的就可以，很奇怪

### ISSUE THREAD

**Issue by Luckbaby** [wocwin/t-ui#17]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/18533218/177522976-ce28ded6-4b4f-4b8d-b1d3-9aa5c0ab35d9.png">
<img width="966" alt="image" src="https://user-images.githubusercontent.com/18533218/177523024-620e3f84-5311-4b25-a2f5-a52843386ba3.png">

**Comment by Luckbaby** [comment]
<img width="997" alt="image" src="https://user-images.githubusercontent.com/18533218/177529901-e6d6cd3d-fb34-49fd-8937-4f06aa0a71b8.png">
有的

**Comment by wocwin** [comment]
你先把我的TTable组件移入你项目中，用我的组件方式使用看看有没有失效，如果没有，应该是你移入代码的问题

**Comment by Luckbaby** [comment]
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/18533218/178183516-099956f9-c9b4-4b63-a8f7-dbe57196c70e.png">
demo中，这两个方法，还是没有效果
