### ISSUE TITLE
this.$refs.baseDataRef.doLayout()is not a function

### ISSUE THREAD

**Issue by Luckbaby** [wocwin/t-ui#18]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/18533218/177977141-b9909dd1-41df-4da2-b91d-599d20de8b92.png">
demo中doLayout()不能使用，单击整行也没有选中效果

**Comment by wocwin** [comment]
> <img alt="image" width="522" src="https://user-images.githubusercontent.com/18533218/177977141-b9909dd1-41df-4da2-b91d-599d20de8b92.png">
> 
> demo中doLayout()不能使用，单击整行也没有选中效果
单选框有单击整行选中的效果，复选框可以做，但实现的效果不佳，而且我这table组件集成了双击单元格复制的功能；至于doLayout方法我现在加上去

**Comment by wocwin** [comment]
> > <img alt="image" width="522" src="https://user-images.githubusercontent.com/18533218/177977141-b9909dd1-41df-4da2-b91d-599d20de8b92.png">
> > demo中doLayout()不能使用，单击整行也没有选中效果
> > 单选框有单击整行选中的效果，复选框可以做，但实现的效果不佳，而且我这table组件集成了双击单元格复制的功能；至于doLayout方法我现在加上去

doLayout()方法已加上你拉一下最新代码；单击整行选中效果你可以参考单选的方式来做
