### ISSUE TITLE
表格整行编辑功能之按钮文案修改

### ISSUE THREAD

**Issue by FOmaerl** [wocwin/t-ui#20]
表格整行编辑功能中添加按钮如何修改文案，比如改为“新增一行”

**Comment by wocwin** [comment]
我新增一个cellEditBtnTxt属性用来修改按钮文案

**Comment by wocwin** [comment]
是不是想要这样的效果
![image](https://user-images.githubusercontent.com/37534478/190382965-92503500-f683-4db2-91b9-50e69044a4a8.png)
；其实我更建议直接用单个单元格编辑功能
