### ISSUE TITLE
t-select-table图片显示问题

### ISSUE THREAD

**Issue by zhaowenjun333** [wocwin/t-ui#24]
动态由后台拼接src,是怎么传入slots里面的。能出个demo吗谢谢。

**Comment by wocwin** [comment]
> 动态由后台拼接src,是怎么传入slots里面的。能出个demo吗谢谢。

你先用TTable组件下的render或插槽的示例试一试，应该是可以实现的，周一上班有时间我在添加示例

**Comment by zhaowenjun333** [comment]
columns: [
                { label: '物料编号', width: '100px', prop: 'code'  , render:()=> { return <img src ="http://localhost:8080/static/img/vue-logo.png"></img>}
                },
                { label: '物料名称', width: '149px', prop: 'name' ,slotName:"scope",},
                { label: '规格', width: '149px', prop: 'spec' },
                { label: '单位', width: '110px', prop: 'unitName' },
                ]
谢谢指点，column里面用原生的render可以。你的api里面有插槽属性，这个用发添加个示例，谢谢。
