### ISSUE TITLE
业务组件--数位顺序表

### ISSUE THREAD

**Issue by jmyz10611210** [wocwin/t-ui#30]
---
名称: 数位顺序表
关于: 财务管理常见记账凭证用
---
关于数位顺序表组件。如下图，数字金额可以修改，输入的数字分割各个位数，插入对应的数位中，注意小数点后2位对应角和分
![image](https://github.com/wocwin/t-ui/assets/62821581/ec4f2346-0ebd-456d-98c3-1dd45d498a9b)
#
[数位顺序表.md](https://github.com/wocwin/t-ui/files/12475723/default.md)

**Comment by wocwin** [comment]
这个特定table,不适合基础组件
