### ISSUE TITLE
t-select-table 回显时没有默认选中

### ISSUE THREAD

**Issue by xzghting** [wocwin/t-ui#42]
设置了defaultSelectVal。
手动去设置组件里面的defaultSelectValue与defaultValue也不行。
需要点一下下拉菜单才能显示。
<img width="562" alt="image" src="https://github.com/wocwin/t-ui/assets/13431205/6d7dac01-d0cd-428a-84a3-0bf1d91f15c5">

**Comment by xzghting** [comment]
![image](https://github.com/wocwin/t-ui/assets/13431205/b0058ab3-2660-47af-96fc-016b807f0693)
有一个报错信息

**Comment by wocwin** [comment]
![image](https://github.com/wocwin/t-ui/assets/37534478/2be80360-4407-45ca-b94a-5d89774d8c3a)
这个值必须在table.data的数据中存在且是字符串类型

**Comment by xzghting** [comment]
解决了，必须得先查一次，才能显示。建议在文档再写清晰一点，table.data要有值

**Comment by wocwin** [comment]
> 解决了，必须得先查一次，才能显示。建议在文档再写清晰一点，table.data要有值

先查一次是什么意思？

**Comment by xzghting** [comment]
就是得先把数据填充

> > 解决了，必须先查一次，才能显示。建议在文档中再写响点，表.data 呼吸值
> 
> 先查一次是什么意思？

**Comment by wocwin** [comment]
> 就是得先把数据填充
> 
> > > 解决了，必须先查一次，才能显示。建议在文档中再写响点，表.data 呼吸值
> > 
> > 
> > 先查一次是什么意思？

不是重新点击下拉框选择咯

**Comment by wocwin** [comment]
> > > 就是得先把数据填充
> > > > > 解决了，必须先查一次，才能显示。建议在文档中再写响点，表.data 呼吸值
> > > > 
> > > > 
> > > > 先查一次是什么意思？
> > 
> > 
> > 不是重新点击下拉框选择咯
> 
> 逻辑是对的，就是table.data里面没有数据，得先填充数据，然后就能回显了

嗯嗯，那回显，肯定得需要赋值table.data，不然怎么回显

**Comment by xzghting** [comment]
> > > > 就是得先把数据填充
> > > > > > 解决了，必须先查一次，才能显示。建议在文档中再写响点，表.data 呼吸值
> > > > > 
> > > > > 
> > > > > 先查一次是什么意思？
> > > 
> > > 
> > > 不是重新点击下拉框选择咯
> > 
> > 
> > 逻辑是对的，就是table.data里面没有数据，得先填充数据，然后就能回显了
> 
> 嗯嗯，那回显，肯定得需要赋值table.data，不然怎么回显

就是有翻页情况就很麻烦了，必须得查指定页😂
