### ISSUE TITLE
t-select-table 里的搜索和重置按钮怎么改为英文

### ISSUE THREAD

**Issue by xbysir** [wocwin/t-ui#46]
t-select-table 里的搜索和重置按钮怎么改为英文
![image](https://github.com/wocwin/t-ui/assets/130360868/531f97c4-6e97-455a-9ebd-34161e5f7bff)

**Comment by wocwin** [comment]
![image](https://github.com/wocwin/t-ui/assets/37534478/c81d3841-bf14-4b85-a7c3-34e91b63edbc)
看文档
