### ISSUE TITLE
TAdaptivePage组件不使用toolbar表格外操作按钮，还是会占空间

### ISSUE THREAD

**Issue by junliangwei** [wocwin/t-ui#47]
![image](https://github.com/wocwin/t-ui/assets/58672206/bbcf363e-7577-43cc-8415-04182a913d17)

**Comment by wocwin** [comment]
已解决，下次发版生效。
![image](https://github.com/wocwin/t-ui/assets/37534478/6a1cdfa7-b6d4-4b05-966d-787ba077ad2f)

**Comment by junliangwei** [comment]
大佬可以在使用文档里。加一个更新日志的记录吗，周围有长期使用的，可以根据更新日志给你反馈一下使用过程中的问题

**Comment by wocwin** [comment]
我看后面加一下Releases
