### ISSUE TITLE
屏幕宽度变小后t-query-condition渲染出错

### ISSUE THREAD

**Issue by burning-33** [wocwin/t-ui#48]
如图：
![image](https://github.com/wocwin/t-ui/assets/33951042/722ad85d-8801-4510-b4ae-44409f9b88d7)

还有是否支持变更每行4列到每行3列

**Comment by burning-33** [comment]
测试了是1280px以下就会发生渲染错误，正常情况下是这样的
![image](https://github.com/wocwin/t-ui/assets/33951042/c0225e0d-02b4-4784-ac7f-5e406e544f0b)

**Comment by wocwin** [comment]
这个不会自动变更，但是你可以自己设置span（默认一行展示4个条件（即4个格子），每一个条件span是1，若span设置2，那么这个条件就占两格，那么这一行就只展示三个条件--span最大值为4---即一个条件占一行）

**Comment by wocwin** [comment]
其实是可以自动变化的，发现grid-template-areas这个样式丢失了

**Comment by wocwin** [comment]
已解决，下次发版生效
